openapi: 3.0.0
info:
  title: Skinvault Marketplace API
  version: "1.0.0"
  description: Documentação da API para o mercado de skins de CS.
servers:
  - url: http://localhost:3333
    description: Servidor de Desenvolvimento

paths:
  # --- Rotas de User e Auth ---
  /users:
    $ref: "./paths/user/users.yaml" # (POST /users, GET /users)
  /session:
    $ref: "./paths/user/session.yaml" # (POST /session)
  /users/{id}:
    $ref: "./paths/user/users_id.yaml" # (GET /users/:id)
  /user/items:
    $ref: "./paths/sellingItem/createSellingItem.yaml"

  # --- Rotas de Inventory ---
  /user/inventory:
    $ref: "./paths/user/user_inventory.yaml" # (GET /user/inventory)

  # --- Rotas de Wallet ---
  /wallet/balance:
    $ref: "./paths/user/wallet_balance.yaml" # (GET /wallet/balance)
  /wallet/transaction:
    $ref: "./paths/user/wallet_transaction.yaml" # (GET /wallet/transaction)

  # --- Category
  /category:
    $ref: "./paths/category/category.yaml"

  # --- Category item
  /category/categoryItem:
    $ref: "./paths/categoryItem/categoryItem.yaml"

  # --- Category Name skin
  /category/categoryItem/categoryNameSkin:
    $ref: "./paths/categoryNameSkin/categoryNameSkin.yaml"

  /categoryNameSkin:
    $ref: "./paths/categoryNameSkin/getAllSkins.yaml"

  /categoryNameSkin/listItemsByCategoryId:
    $ref: "./paths/categoryNameSkin/listItemsByCategoryId.yaml"

  /order:
    $ref: "./paths/order/createOrder.yaml"
  /order/purchase:
    $ref: "./paths/order/createPurchase.yaml"

  #Payment
  /payment/create:
    $ref: "./paths/payment/createCheckout.yaml"

  /webhook/mercado-pago:
    $ref: "./paths/webhook/webHook.yaml"

components:
  # --- Definição da Segurança ---
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "Token JWT Bearer obtido na rota /session."

  # --- CORREÇÃO PRINCIPAL: O Mapa de Schemas ---
  # Esta seção é um MAPA, não um $ref único.
  schemas:
    # Schemas de common.yaml
    UnauthorizedError:
      $ref: "./components/schemas/user/common.yaml#/UnauthorizedError"
    NotFoundError:
      $ref: "./components/schemas/user/common.yaml#/NotFoundError"

    # Schemas de user.yaml
    CreateUserRequest:
      $ref: "./components/schemas/user/user.yaml#/CreateUserRequest"
    UserResponse:
      $ref: "./components/schemas/user/user.yaml#/UserResponse"
    PublicUserResponse:
      $ref: "./components/schemas/user/user.yaml#/PublicUserResponse"
    ErrorResponse:
      $ref: "./components/schemas/user/user.yaml#/ErrorResponse"
    CreateSellingItemRequest:
      $ref: "./components/schemas/sellingItem/createSellingItem.yaml#/CreateSellingItemRequest"
    SellingItemResponseObject:
      $ref: "./components/schemas/sellingItem/createSellingItem.yaml#/SellingItemResponseObject"
    CreateSellingItemResponse:
      $ref: "./components/schemas/sellingItem/createSellingItem.yaml#/CreateSellingItemResponse"
    CreateSellingItemError:
      $ref: "./components/schemas/sellingItem/createSellingItem.yaml#/CreateSellingItemError"

    # Schemas de auth.yaml
    AuthRequest:
      $ref: "./components/schemas/user/auth.yaml#/AuthRequest"
    AuthResponse:
      $ref: "./components/schemas/user/auth.yaml#/AuthResponse"
    AuthError:
      $ref: "./components/schemas/user/auth.yaml#/AuthError"

    # Schemas de inventory.yaml
    InventoryItem:
      $ref: "./components/schemas/user/inventory.yaml#/InventoryItem"
    InventoryResponse:
      $ref: "./components/schemas/user/inventory.yaml#/InventoryResponse"

    # Schemas de wallet.yaml
    WalletBalanceResponse:
      $ref: "./components/schemas/user/wallet.yaml#/WalletBalanceResponse"
    TransactionItem:
      $ref: "./components/schemas/user/wallet.yaml#/TransactionItem"
    WalletTransactionResponse:
      $ref: "./components/schemas/user/wallet.yaml#/WalletTransactionResponse"

    #Category
    CreateCategoryRequest:
      $ref: "./components/schemas/category/category.yaml#/CreateCategoryRequest"
    CategoryResponse:
      $ref: "./components/schemas/category/category.yaml#/CategoryResponse"
    CategoryErrorResponse:
      $ref: "./components/schemas/category/category.yaml#/CategoryErrorResponse"

    #Category Item
    CreateCategoryItemRequest:
      $ref: "./components/schemas/categoryItem/categoryItem.yaml#/CreateCategoryItemRequest"
    CategoryItemResponse:
      $ref: "./components/schemas/categoryItem/categoryItem.yaml#/CategoryItemResponse"
    CategoryItemErrorResponse:
      $ref: "./components/schemas/categoryItem/categoryItem.yaml#/CategoryItemErrorResponse"

    #Category Name Skin
    CategoryNameSkinResponse:
      $ref: "./components/schemas/categoryNameSkin/categoryNameSkin.yaml#/CategoryNameSkinResponse"
    SkinErrorResponse:
      $ref: "./components/schemas/categoryNameSkin/categoryNameSkin.yaml#/SkinErrorResponse"
    GetAllSkinsResponse:
      $ref: "./components/schemas/categoryNameSkin/getAllSkins.yaml#/GetAllSkinsResponse"
    ListSkinsByItemResponse:
      $ref: "./components/schemas/categoryNameSkin/listItemsByCategoryId.yaml#/ListSkinsByItemResponse"

    #Order
    CreateOrderRequest:
      $ref: "./components/schemas/order/createOrder.yaml#/CreateOrderRequest"
    CreateOrderResponse:
      $ref: "./components/schemas/order/createOrder.yaml#/CreateOrderResponse"
    CreateOrderError:
      $ref: "./components/schemas/order/createOrder.yaml#/CreateOrderError"
    OrderResponseObject:
      $ref: "./components/schemas/order/createPurchase.yaml#/OrderResponseObject"
    CreatePurchaseResponse:
      $ref: "./components/schemas/order/createPurchase.yaml#/CreatePurchaseResponse"

    #Payment
    CreatePaymentRequest:
      $ref: "./components/schemas/payment/createCheckout.yaml#/CreatePaymentRequest"
    CreatePaymentResponse:
      $ref: "./components/schemas/payment/createCheckout.yaml#/CreatePaymentResponse"
    CreatePaymentError:
      $ref: "./components/schemas/payment/createCheckout.yaml#/CreatePaymentError"
    #WebHook
    MercadoPagoNotification:
      $ref: "./components/schemas/webhook/webHook.yaml#/MercadoPagoNotification"
    WebhookSuccessResponse:
      $ref: "./components/schemas/webhook/webHook.yaml#/WebhookSuccessResponse"
    WebhookErrorResponse:
      $ref: "./components/schemas/webhook/webHook.yaml#/WebhookErrorResponse"
